### ISSUE TITLE
是否考虑维护

### ISSUE THREAD

**Issue by SoitorDark** [Cyberloafingg/CV-ClassificationHW#1]
是否考虑维护一下，找不到相关模型，和训练文件

**Comment by Cyberloafingg** [comment]
Very sorry, the model file has been lost. You can obtain consistent results as shown in the [PDF](https://github.com/Cyberloafingg/CV-ClassificationHW/blob/main/%E5%9F%BA%E4%BA%8EIP102%E7%9A%84%E6%98%86%E8%99%AB%E5%9B%BE%E5%83%8F%E5%88%86%E7%B1%BB.pdf) in the repository.
